### ISSUE TITLE
Configuration of scheduling services

### ISSUE THREAD

**Issue by floppi-wd** [edgexfoundry/device-scheduling#4]
Hello,
we are implementing for a prototype an edgeX demostrator and have problems to implement the scheduling service. The follow the documentation for implementing but on this way it doesent work. we find some differences between documentation and reality and now we are a little bit confused if something changed in this case. 

We have a Rest-API as device and we can read this api from edgeX. So the implementation of the device works in princip. When we try to schedule the request to this device it happens nothing. We get no errors and nothing in the logs. So the schedule events doesnt work.

```json
Post http://127.0.0.1:48081/api/v1/schedule
{
	"origin": 1234567890,
	"name": "every_minute",
	"start": "",
	"end": "",
	"frequency": "P60S"
}
```
```json
Post http://localhost:48081/api/v1/scheduleevent
{
	"origin": 1234567890,
	"name": "Test2_restapi_scheduleEvent",
	"addressable": {
		"name": "Test1_restapi_address"
	},
	"parameters": null,
	"service": "Test1_restapi_deviceService",
	"schedule": "every_minute"
}
```

What are the wrong by configuration?

**Comment by eb-oss** [comment]
Closing this issue; project is being archived.
